public class JFrame {
    int height;
    int width;
    public Component add() ...
    public void setDefaultCloseOperation() ...
    public void pack() ...
    public void setVisible() ...
    ...
    /** 
     * Construit un nouvel objet Frame invisible par défaut.
    */
   public JFrame(){
    ...
   }
   ...
}